version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db_medilabo
      MYSQL_ROOT_PASSWORD: "@zertyuiop123"
    ports:
      - "3307:3306"

  mysql-db-users:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db_medilabo_users
      MYSQL_ROOT_PASSWORD: "@zertyuiop123"
    ports:
      - "3308:3306"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: notes

  backpatient:
    build:
      context: ./backPatient
    restart: always
    ports:
      - "8085:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/db_medilabo
    depends_on:
      - mysql-db

  backdiabete:
    build:
      context: ./backDiabete
    ports:
      - "8084:8084"

  backnotes:
    build:
      context: ./backNotes
    ports:
      - "8086:8083"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
    depends_on:
      - mongodb

  front:
    build:
      context: ./front
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db-users:3306/db_medilabo_users
    depends_on:
      - mysql-db-users

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - front
      - backpatient
      - backdiabete
      - backnotes
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://front:8081
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: front-route
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/users/**, /signup/**, /login/**, /logout/**, /listUser/**, /home/**, /css/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://backpatient:8082
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: backPatient-route
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path=/patients/**
      SPRING_CLOUD_GATEWAY_ROUTES[2]_URI: http://backdiabete:8084
      SPRING_CLOUD_GATEWAY_ROUTES[2]_ID: backDiabete-route
      SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]: Path=/diabetes/**
      SPRING_CLOUD_GATEWAY_ROUTES[3]_URI: http://backnotes:8083
      SPRING_CLOUD_GATEWAY_ROUTES[3]_ID: backNotes-route
      SPRING_CLOUD_GATEWAY_ROUTES[3]_PREDICATES[0]: Path=/notes/**
